name: Run Tests

on:
  pull_request:
    branches: [ mainline ]

jobs:
  build-shared:
    name: Build Shared Package
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build shared package
        run: npm run build -w shared
      
      - name: Upload shared build
        uses: actions/upload-artifact@v4
        with:
          name: shared-build
          path: shared/dist/
          retention-days: 1

  frontend-tests:
    name: Frontend Unit Tests
    runs-on: ubuntu-latest
    needs: build-shared
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Download shared build
        uses: actions/download-artifact@v4
        with:
          name: shared-build
          path: shared/dist/
      
      - name: Run frontend tests
        run: npm run test:run -w frontend

  frontend-checks:
    name: Frontend Type Check & Lint
    runs-on: ubuntu-latest
    needs: build-shared
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Download shared build
        uses: actions/download-artifact@v4
        with:
          name: shared-build
          path: shared/dist/
      
      - name: Run frontend checks
        run: npm run type-check -w frontend && npm run lint -w frontend

  visual-tests:
    name: Visual Regression Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: build-shared
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Download shared build
        uses: actions/download-artifact@v4
        with:
          name: shared-build
          path: shared/dist/
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: frontend
      
      - name: Run visual regression tests
        run: npm run test:visual -w frontend
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30

  backend-tests:
    name: Backend Tests  
    runs-on: ubuntu-latest
    needs: build-shared
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Download shared build
        uses: actions/download-artifact@v4
        with:
          name: shared-build
          path: shared/dist/
      
      - name: Run backend tests
        run: npm run test:run -w backend
        env:
          NODE_ENV: test
